twig:
  form_themes: ['bootstrap_5_layout.html.twig']
  globals:
    google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'


  default_path: '%kernel.project_dir%/templates'

when@test:
  twig:
    strict_variables: true

